#!/usr/bin/env python3

import argparse
import re
import sys

from dataclasses import dataclass, field
from typing import List


@dataclass
class Subcommand:

    name: str = ""
    desc: str = ""


@dataclass
class Argument:

    name: str = ""
    desc: str = ""

    @property
    def zsh_arg(self):
        return f"':{self.name}:'"


@dataclass
class Option:

    name: str = ""
    alt_name: str = ""
    desc: str = ""
    arg: str = ""

    @property
    def zsh_arg(self):
        """
        Represent an option as a zsh _arguments element.
        """

        if self.alt_name:
            exclusions = f"({self.name} {self.alt_name})"
            if self.arg:
                opt_name = f"{{{self.name}+,{self.alt_name}=}}"
            else:
                opt_name = f"{{{self.name},{self.alt_name}}}"
        else:
            exclusions = f"({self.name})"
            if self.arg:
                opt_name = f"{self.name}="
            else:
                opt_name = f"{self.name}"
        desc = f"[{self.desc}]"
        out = f"'{exclusions}'{opt_name}'{desc}'"

        return out


@dataclass
class HelpParser():

    args: List[Argument] = field(default_factory=list)
    opts: List[Option] = field(default_factory=list)
    subcommands: List[Subcommand] = field(default_factory=list)

    # Argument:
    #
    #   recipename            Name for new recipe to add
    #
    args_re = re.compile(
        r"^  (?P<name>[a-zA-Z]+)"  # argument name
        r"\s+"                     # spaces between name and description
        r"(?P<desc>\S.+)$"         # the description
    )

    # Option with description _not_ on the same line:
    #
    # --srcrev SRCREV, -S SRCREV
    #                   Source revision to fetch...
    #
    opts_re_nodesc = re.compile(
        r"^  (?P<opt1>-[a-zA-Z-]+)"    # the first opt
        r"( (?P<opt_arg>[A-Z_]+))?"    # the first option argument (optional)
        r"( \[[A-Z_]+ \.\.\.\])?"      # additional first option arguments (optional)
        r"(, (?P<opt2>-[a-zA-Z-]+))?"  # the second opt (optional)
        r"( [A-Z_]+)?"                 # the second option argument (optional)
        r"( \[[A-Z_]+ \.\.\.\])?$"     # additional second option arguments (optional)
    )

    # Option with description on the same line:
    #
    #   -h, --help            show this help message and exit
    #
    opts_re_desc = re.compile(
        r"^  (?P<opt1>-[a-zA-Z-]+)"    # the first opt
        r"(( (?P<opt_arg>[A-Z_]+))"    # the first option argument (optional)
        r"|( \.\.\.))?"                # remainder (optional)
        r"(, (?P<opt2>-[a-zA-Z-]+))?"  # the second opt (optional)
        r"( [A-Z_]+)?"                 # the second option argument (optional)
        r"\s+"                         # spaces between opts and description
        r"(?P<desc>\S.+)$"             # the description
    )

    def parse_help(self, help_txt: str) -> None:
        """
        Read a --help command output and parse arguments and options.
        This populates self.opts, self.args or self.subcommands.
        """
        raise NotImplementedError("Do not call parse_help from Parser directly.")

    @property
    def zsh_args(self):
        """
        Print a zsh-completion formatted list of arguments and options.
        """
        out = ""
        for opt in self.opts:
            out += opt.zsh_arg + "\n"
        out += "\n"
        for arg in self.args:
            out += arg.zsh_arg + "\n"
        out = out[:-1]
        return out

    @property
    def opts_oneperline(self):
        """
        Print options in self.opts, one option per line.
        """

        out = ""
        for opt in self.opts:
            out += f"{opt.name}\n"
            if opt.alt_name:
                out += f"{opt.alt_name}\n"
        return out.strip()

    @property
    def subc_oneperline(self):
        """
        Print subcommands in self.subcommands, one subcommand per line.
        """

        out = ""
        for subc in self.subcommands:
            out += f"{subc.name}\n"
        return out.strip()


class BitbakeHelpParser(HelpParser):

    def parse_help(self, help_txt: str) -> None:

        desc_next_line = False
        prev_opt = Option()

        for line in help_txt.splitlines():

            m_desc = re.match(self.opts_re_desc, line)
            m_nodesc = re.match(self.opts_re_nodesc, line)

            if m_nodesc:
                m = m_nodesc
            else:
                m = m_desc

            if desc_next_line:
                desc = line.strip()
                prev_opt.desc = desc[0].lower() + desc[1:]
                desc_next_line = False

            elif m:
                opt = Option()
                desc = ""
                if m_desc and not m_nodesc:
                    desc = m.group("desc")
                if desc:
                    opt.desc = desc[0].lower() + desc[1:]
                opt.arg = m.group("opt_arg")
                opt1, opt2 = m.group("opt1"), m.group("opt2")
                if opt2 is not None:
                    if opt2.startswith("--"):
                        opt.name = opt1
                        opt.alt_name = opt2
                    else:
                        opt.name = opt2
                        opt.alt_name = opt1
                else:
                    opt.name = opt1
                self.opts += [opt]
                if m_nodesc is not None:
                    prev_opt = opt
                    desc_next_line = True

            m_desc, m_nodesc = None, None


class DevtoolHelpParser(HelpParser):

    # Subcommand with description:
    #
    #   add                   Add a new recipe
    #
    subc_re = re.compile(
        r"^    (?P<name>[a-z-]+)"  # the subcommand
        r"\s+"                     # spaces between opts and description
        r"(?P<desc>\S.+)$"         # the description
    )

    def parse_help(self, help_txt: str) -> None:

        in_opts = False
        in_subcommands = False
        desc_next_line = False
        prev_opt = Option()

        for line in help_txt.splitlines():

            if line.startswith("options:"):
                in_subcommands = False
                in_opts = True
                continue

            if line.startswith("subcommands:"):
                in_subcommands = True
                in_opts = False
                continue

            if in_subcommands:
                if m := re.match(self.subc_re, line):
                    self.subcommands += [Subcommand(name=m.group("name"),
                                                    desc=m.group("desc"))]

            if in_opts:
                m_desc = re.match(self.opts_re_desc, line)
                m_nodesc = re.match(self.opts_re_nodesc, line)
                if m_nodesc:
                    m = m_nodesc
                else:
                    m = m_desc

                if desc_next_line:
                    desc = line.strip()
                    prev_opt.desc = desc[0].lower() + desc[1:]
                    desc_next_line = False

                elif m:
                    opt = Option()
                    desc = ""
                    if m_desc and not m_nodesc:
                        desc = m.group("desc")
                    if desc:
                        opt.desc = desc[0].lower() + desc[1:]
                    opt.arg = m.group("opt_arg")
                    opt1, opt2 = m.group("opt1"), m.group("opt2")
                    if opt2 is not None:
                        if opt2.startswith("--"):
                            opt.name = opt1
                            opt.alt_name = opt2
                        else:
                            opt.name = opt2
                            opt.alt_name = opt1
                    else:
                        opt.name = opt1
                    self.opts += [opt]
                    if m_nodesc is not None:
                        prev_opt = opt
                        desc_next_line = True

                m_desc, m_nodesc = None, None


class DevtoolSubcommandHelpParser(HelpParser):

    def parse_help(self, help_txt: str) -> None:

        in_args = False
        in_opts = False
        desc_next_line = False
        prev_opt = Option()

        for line in help_txt.splitlines():

            if line.startswith("arguments:"):
                in_args = True
                in_opts = False
                continue

            if line.startswith("options:"):
                in_args = False
                in_opts = True
                continue

            if in_args:
                if m := re.match(self.args_re, line):
                    self.args += [Argument(name=m.group("name"),
                                           desc=m.group("desc"))]

            if in_opts:
                m_desc = re.match(self.opts_re_desc, line)
                m_nodesc = re.match(self.opts_re_nodesc, line)
                if m_nodesc:
                    m = m_nodesc
                else:
                    m = m_desc

                if desc_next_line:
                    desc = line.strip()
                    prev_opt.desc = desc[0].lower() + desc[1:]
                    desc_next_line = False

                elif m:
                    opt = Option()
                    desc = ""
                    if m_desc and not m_nodesc:
                        desc = m.group("desc")
                    if desc:
                        opt.desc = desc[0].lower() + desc[1:]
                    opt.arg = m.group("opt_arg")
                    opt1, opt2 = m.group("opt1"), m.group("opt2")
                    if opt2 is not None:
                        if opt2.startswith("--"):
                            opt.name = opt1
                            opt.alt_name = opt2
                        else:
                            opt.name = opt2
                            opt.alt_name = opt1
                    else:
                        opt.name = opt1
                    self.opts += [opt]
                    if m_nodesc is not None:
                        prev_opt = opt
                        desc_next_line = True

                m_desc, m_nodesc = None, None


def print_opts_zsh(text: str, indent: int = 0):
    """
    Helper function to call a Parser's zsh_args + some left indentation, for
    easier copy-pasting in completion file.
    """
    for line in text.splitlines():
        print(" " * indent + line)


def parse_arguments() -> argparse.ArgumentParser:

    parser = argparse.ArgumentParser(
        description="Parse bitbake-like tools help messages")

    parser.add_argument("--print-opts",
                        action="store_true",
                        default=False,
                        dest="print_opts",
                        help="Print options (one per line)")

    parser.add_argument("--print-subcommands",
                        action="store_true",
                        default=False,
                        dest="print_subcommands",
                        help="Print subcommands (one per line)")

    parser.add_argument("--print-args-zsh",
                        action="store_true",
                        default=False,
                        dest="print_opts_zsh",
                        help="Print parsed help as zsh arguments")

    parser.add_argument("--parse-mode",
                        choices=[
                            "bitbake",
                            "devtool",
                            "devtool.subcommand",
                        ],
                        dest="mode",
                        required=True,
                        help="Parsing mode")

    parser.add_argument("--indent",
                        type=int,
                        default=0,
                        help="How much to indent the output for zsh output")

    return parser


def main():

    aparser = parse_arguments()
    pargs = aparser.parse_args()

    help_txt = sys.stdin.read()
    if not help_txt:
        print("No test passed in stdin!")
        aparser.print_usage()
        exit(1)

    parser = HelpParser()

    if pargs.mode == "bitbake":
        parser = BitbakeHelpParser()

    if pargs.mode == "devtool":
        parser = DevtoolHelpParser()

    if pargs.mode == "devtool.subcommand":
        parser = DevtoolSubcommandHelpParser()

    parser.parse_help(help_txt)

    if pargs.print_opts_zsh:
        print_opts_zsh(parser.zsh_args, pargs.indent)

    if pargs.print_opts:
        print(parser.opts_oneperline)

    if pargs.print_subcommands:
        print(parser.subc_oneperline)


if __name__ == "__main__":
    main()
