#!/usr/bin/env bash
#
# Run test-complete against all supported tools.

main() {
  local ret=0
  local test_complete="${1:-ci/test-complete}"
  local help_parser="${2:-ci/parse-help}"
  local oe_init="${3:-oecore/oe-init-build-env}"
  local -a subcommands

  # Setup environment - do not change directory.
  # oecore should be cloned by now.
  source "$oe_init" .

  $test_complete bitbake || ret=1
  $test_complete devtool || ret=1
  $test_complete devtool subcommands || ret=1

  # Fetch subcommands with parse-help
  mapfile -t subcommands < <(
    COLUMNS=7000 devtool --help |
    $help_parser --parse-mode devtool --print-subcommands
  )

  for subc in "${subcommands[@]}"; do
    $test_complete devtool "$subc" || ret=1
  done

  exit $ret
}

main "$@"
